// This file is generated automatically by Next.js
// Do not edit this file manually

// Type definitions for Next.js routes

/**
 * Internal types used by the Next.js router and Link component.
 * These types are not meant to be used directly.
 * @internal
 */
declare namespace __next_route_internal_types__ {
  type SearchOrHash = `?${string}` | `#${string}`
  type WithProtocol = `${string}:${string}`

  type Suffix = '' | SearchOrHash

  type SafeSlug<S extends string> = S extends `${string}/${string}`
    ? never
    : S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type CatchAllSlug<S extends string> = S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type OptionalCatchAllSlug<S extends string> =
    S extends `${string}${SearchOrHash}` ? never : S

  type StaticRoutes = 
    | `/`
    | `/admin`
    | `/admin/dev-dashboard`
    | `/admin/fonts`
    | `/admin/games`
    | `/admin/groups`
    | `/admin/networks`
    | `/admin/scrape-images`
    | `/admin/settings`
    | `/admin/shows`
    | `/admin/social-media`
    | `/admin/social-media/bravo-content`
    | `/admin/social-media/creator-content`
    | `/admin/survey-responses`
    | `/admin/surveys`
    | `/admin/surveys/normalized`
    | `/admin/trr-shows`
    | `/admin/users`
    | `/api/admin/auth/status`
    | `/api/admin/auth/status/drill-report`
    | `/api/admin/auth/status/reset`
    | `/api/admin/covered-shows`
    | `/api/admin/dev-dashboard`
    | `/api/admin/networks-streaming/detail`
    | `/api/admin/networks-streaming/overrides`
    | `/api/admin/networks-streaming/summary`
    | `/api/admin/networks-streaming/sync`
    | `/api/admin/normalized-surveys`
    | `/api/admin/reddit/communities`
    | `/api/admin/reddit/threads`
    | `/api/admin/scrape/import`
    | `/api/admin/scrape/import/stream`
    | `/api/admin/scrape/preview`
    | `/api/admin/shows`
    | `/api/admin/surveys`
    | `/api/admin/trr-api/assets/archive`
    | `/api/admin/trr-api/assets/content-type`
    | `/api/admin/trr-api/assets/star`
    | `/api/admin/trr-api/media-links`
    | `/api/admin/trr-api/people`
    | `/api/admin/trr-api/people/resolve-slug`
    | `/api/admin/trr-api/shows`
    | `/api/admin/trr-api/shows/resolve-slug`
    | `/api/admin/trr-api/shows/sync-from-lists`
    | `/api/cron/create-survey-runs`
    | `/api/cron/episode-progression`
    | `/api/debug-log`
    | `/api/session/login`
    | `/api/session/logout`
    | `/api/shows/list`
    | `/api/surveys/global-profile`
    | `/api/surveys/show-responses`
    | `/api/surveys/x`
    | `/auth/complete`
    | `/auth/finish`
    | `/auth/forgot-password`
    | `/auth/register`
    | `/bravodle`
    | `/bravodle/cover`
    | `/bravodle/play`
    | `/hub`
    | `/hub/surveys`
    | `/login`
    | `/privacy-policy`
    | `/profile`
    | `/realations`
    | `/realitease`
    | `/realitease/cover`
    | `/realitease/play`
    | `/surveys/cast-verdict-demo`
    | `/surveys/rhop-s10`
    | `/surveys/rhop-s10/play`
    | `/surveys/rhop-s10/results`
    | `/surveys/rhoslc-s6`
    | `/surveys/rhoslc-s6/play`
    | `/surveys/rhoslc-s6/results`
    | `/terms-of-sale`
    | `/terms-of-service`
    | `/test-auth`
  type DynamicRoutes<T extends string = string> = 
    | `/admin/networks/${SafeSlug<T>}/${SafeSlug<T>}`
    | `/admin/social-media/reddit/communities/${SafeSlug<T>}`
    | `/admin/surveys/${SafeSlug<T>}`
    | `/admin/surveys/normalized/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/${SafeSlug<T>}/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/assets`
    | `/admin/trr-shows/${SafeSlug<T>}/assets/brand`
    | `/admin/trr-shows/${SafeSlug<T>}/assets/images`
    | `/admin/trr-shows/${SafeSlug<T>}/assets/videos`
    | `/admin/trr-shows/${SafeSlug<T>}/cast`
    | `/admin/trr-shows/${SafeSlug<T>}/details`
    | `/admin/trr-shows/${SafeSlug<T>}/news`
    | `/admin/trr-shows/${SafeSlug<T>}/overview`
    | `/admin/trr-shows/${SafeSlug<T>}/people/${SafeSlug<T>}/${OptionalCatchAllSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/assets`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/assets/brand`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/assets/media`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/cast`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/details`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/episodes`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/week/${SafeSlug<T>}`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/surveys`
    | `/admin/trr-shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/videos`
    | `/admin/trr-shows/${SafeSlug<T>}/settings`
    | `/admin/trr-shows/${SafeSlug<T>}/social`
    | `/admin/trr-shows/${SafeSlug<T>}/surveys`
    | `/admin/trr-shows/people/${SafeSlug<T>}`
    | `/api/admin/covered-shows/${SafeSlug<T>}`
    | `/api/admin/images/${SafeSlug<T>}/${SafeSlug<T>}`
    | `/api/admin/images/${SafeSlug<T>}/${SafeSlug<T>}/archive`
    | `/api/admin/images/${SafeSlug<T>}/${SafeSlug<T>}/reassign`
    | `/api/admin/networks-streaming/overrides/${SafeSlug<T>}`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/questions`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/questions/${SafeSlug<T>}`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/questions/${SafeSlug<T>}/options`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/runs`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/runs/${SafeSlug<T>}`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/runs/${SafeSlug<T>}/export`
    | `/api/admin/normalized-surveys/${SafeSlug<T>}/runs/${SafeSlug<T>}/responses`
    | `/api/admin/reddit/communities/${SafeSlug<T>}`
    | `/api/admin/reddit/communities/${SafeSlug<T>}/discover`
    | `/api/admin/reddit/communities/${SafeSlug<T>}/episode-discussions/refresh`
    | `/api/admin/reddit/communities/${SafeSlug<T>}/episode-discussions/save`
    | `/api/admin/reddit/communities/${SafeSlug<T>}/flares/refresh`
    | `/api/admin/reddit/threads/${SafeSlug<T>}`
    | `/api/admin/shows/${SafeSlug<T>}`
    | `/api/admin/shows/${SafeSlug<T>}/seasons`
    | `/api/admin/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}`
    | `/api/admin/shows/by-trr-show/${SafeSlug<T>}`
    | `/api/admin/social-posts/${SafeSlug<T>}`
    | `/api/admin/surveys/${SafeSlug<T>}`
    | `/api/admin/surveys/${SafeSlug<T>}/cast`
    | `/api/admin/surveys/${SafeSlug<T>}/cast/${SafeSlug<T>}`
    | `/api/admin/surveys/${SafeSlug<T>}/cast/reorder`
    | `/api/admin/surveys/${SafeSlug<T>}/episodes`
    | `/api/admin/surveys/${SafeSlug<T>}/episodes/${SafeSlug<T>}`
    | `/api/admin/surveys/${SafeSlug<T>}/episodes/${SafeSlug<T>}/activate`
    | `/api/admin/surveys/${SafeSlug<T>}/export`
    | `/api/admin/surveys/${SafeSlug<T>}/responses`
    | `/api/admin/surveys/${SafeSlug<T>}/responses/${SafeSlug<T>}`
    | `/api/admin/surveys/${SafeSlug<T>}/theme`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/auto-count`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/detect-text-overlay`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/mirror`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/people-count`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/tags`
    | `/api/admin/trr-api/cast-photos/${SafeSlug<T>}/variants`
    | `/api/admin/trr-api/media-assets/${SafeSlug<T>}`
    | `/api/admin/trr-api/media-assets/${SafeSlug<T>}/auto-count`
    | `/api/admin/trr-api/media-assets/${SafeSlug<T>}/detect-text-overlay`
    | `/api/admin/trr-api/media-assets/${SafeSlug<T>}/mirror`
    | `/api/admin/trr-api/media-assets/${SafeSlug<T>}/variants`
    | `/api/admin/trr-api/media-links/${SafeSlug<T>}/context`
    | `/api/admin/trr-api/media-links/${SafeSlug<T>}/tags`
    | `/api/admin/trr-api/people/${SafeSlug<T>}`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/cover-photo`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/credits`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/fandom`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/gallery/${SafeSlug<T>}/facebank-seed`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/import-fandom/commit`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/import-fandom/preview`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/photos`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/photos/${SafeSlug<T>}/thumbnail-crop`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/refresh-images`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/refresh-images/stream`
    | `/api/admin/trr-api/people/${SafeSlug<T>}/reprocess-images/stream`
    | `/api/admin/trr-api/seasons/${SafeSlug<T>}/assign-backdrops`
    | `/api/admin/trr-api/seasons/${SafeSlug<T>}/episodes`
    | `/api/admin/trr-api/seasons/${SafeSlug<T>}/unassigned-backdrops`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/assets`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/assets/batch-jobs/stream`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/auto-count-images`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/bravo/news`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/bravo/videos`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/bravo/videos/sync-thumbnails`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/cast`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/cast-matrix/sync`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/cast-role-members`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/cast/${SafeSlug<T>}/roles`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/google-news/sync`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/google-news/sync/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/import-bravo/commit`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/import-bravo/preview`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/import-bravo/preview/stream`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/links`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/links/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/links/discover`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/news`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/refresh`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/refresh-photos/stream`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/refresh/stream`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/roles`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/roles/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/assets`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/assets/batch-jobs/stream`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/cast`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/fandom`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/import-fandom/commit`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/import-fandom/preview`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/analytics`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/analytics/comments-coverage`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/analytics/posts/${SafeSlug<T>}/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/analytics/week/${SafeSlug<T>}`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/export`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/ingest`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/ingest/runs/${SafeSlug<T>}/cancel`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/jobs`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/runs`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/runs/summary`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/social/targets`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/seasons/${SafeSlug<T>}/survey-cast`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/social-posts`
    | `/api/admin/trr-api/shows/${SafeSlug<T>}/surveys`
    | `/api/surveys/${SafeSlug<T>}/active-run`
    | `/api/surveys/${SafeSlug<T>}/submit`
    | `/surveys/n/${SafeSlug<T>}/play`

  type RouteImpl<T> = 
    | StaticRoutes
    | SearchOrHash
    | WithProtocol
    | `${StaticRoutes}${SearchOrHash}`
    | (T extends `${DynamicRoutes<infer _>}${Suffix}` ? T : never)
    
}

declare module 'next' {
  export { default } from 'next/types.js'
  export * from 'next/types.js'

  export type Route<T extends string = string> =
    __next_route_internal_types__.RouteImpl<T>
}

declare module 'next/link' {
  export { useLinkStatus } from 'next/dist/client/link.js'

  import type { LinkProps as OriginalLinkProps } from 'next/dist/client/link.js'
  import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
  import type { UrlObject } from 'url'

  type LinkRestProps = Omit<
    Omit<
      DetailedHTMLProps<
        AnchorHTMLAttributes<HTMLAnchorElement>,
        HTMLAnchorElement
      >,
      keyof OriginalLinkProps
    > &
      OriginalLinkProps,
    'href'
  >

  export type LinkProps<RouteInferType> = LinkRestProps & {
    /**
     * The path or URL to navigate to. This is the only required prop. It can also be an object.
     * @see https://nextjs.org/docs/api-reference/next/link
     */
    href: __next_route_internal_types__.RouteImpl<RouteInferType> | UrlObject
  }

  export default function Link<RouteType>(props: LinkProps<RouteType>): JSX.Element
}

declare module 'next/navigation' {
  export * from 'next/dist/client/components/navigation.js'

  import type { NavigateOptions, AppRouterInstance as OriginalAppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime.js'
  import type { RedirectType } from 'next/dist/client/components/redirect-error.js'
  
  interface AppRouterInstance extends OriginalAppRouterInstance {
    /**
     * Navigate to the provided href.
     * Pushes a new history entry.
     */
    push<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Navigate to the provided href.
     * Replaces the current history entry.
     */
    replace<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Prefetch the provided href.
     */
    prefetch<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>): void
  }

  export function useRouter(): AppRouterInstance;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 307/303 to the caller.
   * - In a Server Action, type defaults to 'push' and 'replace' elsewhere.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function redirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 308/303 to the caller.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function permanentRedirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
}

declare module 'next/form' {
  import type { FormProps as OriginalFormProps } from 'next/dist/client/form.js'

  type FormRestProps = Omit<OriginalFormProps, 'action'>

  export type FormProps<RouteInferType> = {
    /**
     * `action` can be either a `string` or a function.
     * - If `action` is a string, it will be interpreted as a path or URL to navigate to when the form is submitted.
     *   The path will be prefetched when the form becomes visible.
     * - If `action` is a function, it will be called when the form is submitted. See the [React docs](https://react.dev/reference/react-dom/components/form#props) for more.
     */
    action: __next_route_internal_types__.RouteImpl<RouteInferType> | ((formData: FormData) => void)
  } & FormRestProps

  export default function Form<RouteType>(props: FormProps<RouteType>): JSX.Element
}
