import type { Metadata } from "next";
import { Geist, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import "./side-menu.css";
import ToastHost from "@/components/ToastHost";
import ErrorBoundary from "@/components/ErrorBoundary";
import DebugPanel from "@/components/DebugPanel";
import SideMenuProvider from "@/components/SideMenuProvider";
import TypographyRuntimeClient from "@/components/typography/TypographyRuntimeClient";
import {
  HOSTED_FONT_PRELOADS,
  buildHostedFontAssetPath,
} from "@/lib/fonts/hosted-fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "The Reality Report",
  description: "News, surveys, polls, quizzes, and games for Reality TV fans.",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line @next/next/no-css-tags -- hosted fonts are generated by a same-origin runtime CSS route */}
        <link rel="stylesheet" href="/hosted-fonts.css" />
        {HOSTED_FONT_PRELOADS.map((preload) => (
          <link
            key={preload.assetPath}
            rel="preload"
            href={buildHostedFontAssetPath(preload.assetPath)}
            as="font"
            type={preload.type}
            crossOrigin="anonymous"
          />
        ))}
      </head>
      <body className={`${geistSans.variable} ${inter.variable} ${playfair.variable} font-sans antialiased`}>
        <TypographyRuntimeClient>
          <SideMenuProvider>
            <ErrorBoundary>
              <ToastHost />
              {children}
              <DebugPanel />
            </ErrorBoundary>
          </SideMenuProvider>
        </TypographyRuntimeClient>
      </body>
    </html>
  );
}
