export const DESIGN_SYSTEM_COLORS_STORAGE_KEY = "trr.design-system-base-colors";

export const DESIGN_SYSTEM_BASE_COLORS = [
  "#7A0307",
  "#95164A",
  "#B81D22",
  "#CF5315",
  "#C76D00",
  "#F1991B",
  "#B05E2A",
  "#E3A320",
  "#D48C42",
  "#ECC91C",
  "#977022",
  "#744A1F",
  "#C2B72D",
  "#76A34C",
  "#356A3B",
  "#0C454A",
  "#769F25",
  "#A1C6D4",
  "#53769C",
  "#4B7C89",
  "#28578A",
  "#063656",
  "#1D4782",
  "#2C438D",
  "#144386",
  "#6568AB",
  "#644072",
  "#4F2F4B",
  "#C37598",
  "#B05988",
  "#644073",
  "#772149",
  "#DFC3D9",
  "#E9A6C7",
  "#A5739F",
  "#D37EAF",
  "#C8BEB3",
  "#D2C09E",
  "#666A6E",
  "#34130C",
  "#34373F",
  "#35110B",
] as const;

export const DESIGN_SYSTEM_CDN_FONT_OPTIONS = [
  { name: "Beton", fontFamily: "\"Beton\", var(--font-sans), sans-serif" },
  { name: "Biotif Pro", fontFamily: "\"Biotif Pro\", var(--font-sans), sans-serif" },
  { name: "Cheltenham", fontFamily: "\"Cheltenham\", var(--font-sans), sans-serif" },
  { name: "Cheltenham Old Style Pro", fontFamily: "\"Cheltenham Old Style Pro\", var(--font-sans), sans-serif" },
  { name: "Chomsky", fontFamily: "\"Chomsky\", var(--font-sans), sans-serif" },
  { name: "Franklin Gothic", fontFamily: "\"Franklin Gothic\", var(--font-sans), sans-serif" },
  { name: "Franklin Gothic Raw", fontFamily: "\"Franklin Gothic Raw\", var(--font-sans), sans-serif" },
  { name: "Futura Now", fontFamily: "\"Futura Now\", var(--font-sans), sans-serif" },
  { name: "Geometric Slabserif 703", fontFamily: "\"Geometric Slabserif 703\", var(--font-sans), sans-serif" },
  { name: "Geometric Slabserif 712", fontFamily: "\"Geometric Slabserif 712\", var(--font-sans), sans-serif" },
  { name: "Gloucester", fontFamily: "\"Gloucester\", var(--font-sans), sans-serif" },
  { name: "Goodall", fontFamily: "\"Goodall\", var(--font-sans), sans-serif" },
  { name: "Hamburg Serial", fontFamily: "\"Hamburg Serial\", \"HamburgSerial\", var(--font-sans), sans-serif" },
  { name: "ITC Cheltenham", fontFamily: "\"ITC Cheltenham\", var(--font-sans), sans-serif" },
  { name: "ITC Franklin Gothic LT", fontFamily: "\"ITC Franklin Gothic LT\", var(--font-sans), sans-serif" },
  { name: "Magnus", fontFamily: "\"Magnus\", var(--font-sans), sans-serif" },
  { name: "Malden Sans", fontFamily: "\"Malden Sans\", var(--font-sans), sans-serif" },
  { name: "News Gothic", fontFamily: "\"News Gothic\", var(--font-sans), sans-serif" },
  { name: "News Gothic No. 2", fontFamily: "\"News Gothic No. 2\", var(--font-sans), sans-serif" },
  { name: "Newspaper Publisher JNL", fontFamily: "\"Newspaper Publisher JNL\", var(--font-sans), sans-serif" },
  { name: "Newston", fontFamily: "\"Newston\", var(--font-sans), sans-serif" },
  { name: "Plymouth Serial", fontFamily: "\"Plymouth Serial\", var(--font-sans), sans-serif" },
  { name: "Rockwell", fontFamily: "\"Rockwell\", var(--font-sans), sans-serif" },
  { name: "Rockwell Nova", fontFamily: "\"Rockwell Nova\", var(--font-sans), sans-serif" },
  { name: "Rude Slab Condensed", fontFamily: "\"Rude Slab Condensed\", var(--font-sans), sans-serif" },
  { name: "Sofia Pro", fontFamily: "\"Sofia Pro\", var(--font-sans), sans-serif" },
  { name: "Stafford Serial", fontFamily: "\"Stafford Serial\", var(--font-sans), sans-serif" },
  { name: "Stymie", fontFamily: "\"Stymie\", var(--font-sans), sans-serif" },
  { name: "Stymie Extra Bold", fontFamily: "\"Stymie Extra Bold\", var(--font-sans), sans-serif" },
  { name: "Velino Compressed Text", fontFamily: "\"Velino Compressed Text\", var(--font-sans), sans-serif" },
] as const;
