import type { AdminApiReferenceCatalogOverrides } from "./types.ts";

export const ADMIN_API_REFERENCE_OVERRIDES: AdminApiReferenceCatalogOverrides = {
  nodeOverrides: [
    {
      id: "page:/admin",
      usageTier: "manual",
      staticOnly: true,
      basis: ["manual_override:admin_dashboard_reference_container"],
    },
    {
      id: "page:/admin/api-references",
      usageTier: "manual",
      staticOnly: true,
      basis: ["manual_override:reference_library_page"],
    },
    {
      id: "page:/admin/docs",
      usageTier: "low",
      staticOnly: true,
      basis: ["manual_override:documentation_reference_surface"],
    },
    {
      id: "page:/admin/fonts",
      usageTier: "low",
      staticOnly: true,
      basis: ["manual_override:design_reference_surface"],
    },
    {
      id: "page:/admin/design-docs/[section]",
      usageTier: "low",
      staticOnly: true,
      basis: ["manual_override:design_reference_surface"],
    },
    {
      id: "route:GET:/api/admin/trr-api/operations/health",
      usageTier: "high",
      basis: ["manual_override:health_checks_and_live_status"],
    },
    {
      id: "route:GET:/api/admin/networks-streaming/summary",
      usageTier: "high",
      loadsLargeDatasets: true,
      basis: ["manual_override:brand_summary_dashboard"],
    },
    {
      id: "route:GET:/api/admin/covered-shows",
      usageTier: "medium",
      basis: ["manual_override:frequent_admin_list_fetch"],
    },
    {
      id: "route:GET:/api/admin/surveys/[surveyKey]/responses",
      usageTier: "medium",
      loadsLargeDatasets: true,
      usesPagination: true,
      returnsWideRowsOrBlobsOrRawJson: true,
      viewKinds: ["list", "detail"],
      basis: ["manual_override:survey_response_table"],
    },
    {
      id: "route:GET:/api/admin/surveys/[surveyKey]/responses/[responseId]",
      usageTier: "medium",
      returnsWideRowsOrBlobsOrRawJson: true,
      viewKinds: ["detail"],
      basis: ["manual_override:survey_response_detail"],
    },
    {
      id: "route:GET:/api/admin/surveys/[surveyKey]/export",
      usageTier: "low",
      automatic: false,
      returnsWideRowsOrBlobsOrRawJson: true,
      basis: ["manual_override:user_triggered_export_blob"],
    },
    {
      id: "route:GET:/api/admin/scrape/import/stream",
      usageTier: "high",
      automatic: true,
      polls: true,
      basis: ["manual_override:sse_stream_for_import_progress"],
    },
    {
      id: "route:GET:/api/admin/trr-api/operations/[operationId]/stream",
      usageTier: "continuous",
      automatic: true,
      polls: true,
      basis: ["manual_override:operation_stream_progress"],
    },
    {
      id: "route:GET:/api/admin/trr-api/shows/[showId]/assets/batch-jobs/stream",
      usageTier: "continuous",
      automatic: true,
      polls: true,
      basis: ["manual_override:batch_job_stream_progress"],
    },
    {
      id: "route:GET:/api/admin/trr-api/people/[personId]/refresh-images/stream",
      usageTier: "continuous",
      automatic: true,
      polls: true,
      basis: ["manual_override:person_refresh_stream_progress"],
    },
    {
      id: "backend:GET:/api/v1/admin/operations/health",
      usageTier: "high",
      basis: ["manual_override:backend_health_surface"],
    },
    {
      id: "backend:GET:/api/v1/admin/brands/families/by-entity",
      usageTier: "medium",
      basis: ["manual_override:brands_family_lookup"],
    },
  ],
  seedNodes: [
    {
      id: "backend:GET:/api/v2/admin/people/[personId]/external-ids",
      kind: "backend_endpoint",
      title: "GET /api/v2/admin/people/[personId]/external-ids",
      pathPattern: "/api/v2/admin/people/[personId]/external-ids",
      symbol: "GET",
      sourceFile: "src/lib/server/trr-api/admin-external-id-reads.ts",
      sourceLocator: { line: 185, symbol: "listPersonExternalIds" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
      usageTier: "manual",
      polls: false,
      pollCadenceMs: null,
      automatic: false,
      loadsLargeDatasets: false,
      usesPagination: false,
      returnsWideRowsOrBlobsOrRawJson: false,
      fansOutQueries: false,
      postgresAccess: "indirect",
      viewKinds: ["detail"],
      staticOnly: false,
    },
    {
      id: "backend:POST:/api/v2/admin/people/external-ids/batch",
      kind: "backend_endpoint",
      title: "POST /api/v2/admin/people/external-ids/batch",
      pathPattern: "/api/v2/admin/people/external-ids/batch",
      symbol: "POST",
      sourceFile: "src/lib/server/trr-api/admin-external-id-reads.ts",
      sourceLocator: { line: 214, symbol: "listPrimaryPersonExternalIdsByPersonIds" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
      usageTier: "medium",
      polls: false,
      pollCadenceMs: null,
      automatic: false,
      loadsLargeDatasets: true,
      usesPagination: false,
      returnsWideRowsOrBlobsOrRawJson: true,
      fansOutQueries: false,
      postgresAccess: "indirect",
      viewKinds: ["list"],
      staticOnly: false,
    },
    {
      id: "backend:POST:/api/v2/admin/shows/external-ids/batch",
      kind: "backend_endpoint",
      title: "POST /api/v2/admin/shows/external-ids/batch",
      pathPattern: "/api/v2/admin/shows/external-ids/batch",
      symbol: "POST",
      sourceFile: "src/lib/server/trr-api/admin-external-id-reads.ts",
      sourceLocator: { line: 265, symbol: "listShowExternalIdsByIds" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
      usageTier: "medium",
      polls: false,
      pollCadenceMs: null,
      automatic: false,
      loadsLargeDatasets: true,
      usesPagination: false,
      returnsWideRowsOrBlobsOrRawJson: true,
      fansOutQueries: false,
      postgresAccess: "indirect",
      viewKinds: ["list"],
      staticOnly: false,
    },
    {
      id: "repo:src/lib/server/admin/brand-profile-repository.ts::module",
      kind: "repository_surface",
      title: "brand-profile-repository module",
      pathPattern: null,
      symbol: "module",
      sourceFile: "src/lib/server/admin/brand-profile-repository.ts",
      sourceLocator: { line: 1, symbol: "module" },
      provenance: "manual_override",
      confidence: "medium",
      verificationStatus: "unverified_manual",
      basis: ["manual_override:backend_repository_mapping_seed"],
      usageTier: "manual",
      polls: false,
      pollCadenceMs: null,
      automatic: false,
      loadsLargeDatasets: false,
      usesPagination: false,
      returnsWideRowsOrBlobsOrRawJson: false,
      fansOutQueries: false,
      postgresAccess: "direct",
      viewKinds: [],
      staticOnly: false,
    },
  ],
  edgeOverrides: [
    {
      kind: "proxies_to",
      from: "route:GET:/api/admin/trr-api/people/[personId]/external-ids",
      to: "backend:GET:/api/v2/admin/people/[personId]/external-ids",
      sourceFile: "src/lib/server/trr-api/admin-external-id-reads.ts",
      sourceLocator: { line: 185, symbol: "listPersonExternalIds" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "proxies_to",
      from: "route:POST:/api/admin/social/landing",
      to: "backend:GET:/api/v2/admin/people/[personId]/external-ids",
      sourceFile: "src/app/api/admin/social/landing/route.ts",
      sourceLocator: { line: 678, symbol: "POST" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "proxies_to",
      from: "route:GET:/api/admin/social/landing",
      to: "backend:POST:/api/v2/admin/people/external-ids/batch",
      sourceFile: "src/lib/server/admin/social-landing-repository.ts",
      sourceLocator: { line: 1195, symbol: "getSocialLandingPayloadResult" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "proxies_to",
      from: "route:POST:/api/admin/social/landing",
      to: "backend:POST:/api/v2/admin/people/external-ids/batch",
      sourceFile: "src/lib/server/admin/social-landing-repository.ts",
      sourceLocator: { line: 1195, symbol: "getSocialLandingPayloadResult" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "proxies_to",
      from: "route:GET:/api/admin/social/landing",
      to: "backend:POST:/api/v2/admin/shows/external-ids/batch",
      sourceFile: "src/lib/server/admin/social-landing-repository.ts",
      sourceLocator: { line: 1136, symbol: "getSocialLandingPayloadResult" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "proxies_to",
      from: "route:POST:/api/admin/social/landing",
      to: "backend:POST:/api/v2/admin/shows/external-ids/batch",
      sourceFile: "src/lib/server/admin/social-landing-repository.ts",
      sourceLocator: { line: 1136, symbol: "getSocialLandingPayloadResult" },
      provenance: "manual_override",
      confidence: "high",
      verificationStatus: "verified",
      basis: ["manual_override:verified_indirect_v2_client_mapping"],
    },
    {
      kind: "touches_repository",
      from: "backend:GET:/api/v1/admin/brands/families/by-entity",
      to: "repo:src/lib/server/admin/brand-profile-repository.ts::module",
      provenance: "manual_override",
      confidence: "medium",
      verificationStatus: "unverified_manual",
      basis: ["manual_override:backend_family_lookup_repository_mapping"],
    },
  ],
};
