import type { BrandFontMatchRule, BrandFontSeed } from "./types.ts";

export const BRAND_FONT_REGISTRY_SEED: readonly BrandFontSeed[] = [
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Recipe Titles",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:203",
      "brand-nyt-cooking:specimen-meta:216",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Collection Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:232",
      "brand-nyt-cooking:specimen-meta:245",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Body / Instructions",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:261",
      "brand-nyt-cooking:specimen-meta:278",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Ingredient List",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular", "Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:294",
      "brand-nyt-cooking:specimen-meta:309",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Step Numbers",
    roleType: "ui",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:325",
      "brand-nyt-cooking:specimen-meta:349",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Tags",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:397",
      "brand-nyt-cooking:specimen-meta:419",
    ],
  },
  {
    brandId: "brand-nyt-cooking",
    brandLabel: "NYT Cooking",
    roleLabel: "Notes / Tips",
    roleType: "caption",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-cooking:jsx-label:365",
      "brand-nyt-cooking:specimen-meta:381",
    ],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Cover Display",
    roleType: "display",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Black"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:136"],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Feature Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:200"],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Deck / Subhead",
    roleType: "subhead",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:246"],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Body",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:294"],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Captions",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:351"],
  },
  {
    brandId: "brand-nyt-magazine",
    brandLabel: "NYT Magazine",
    roleLabel: "Byline",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Medium"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-magazine:jsx-label:396"],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Column Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:175",
      "brand-nyt-opinion:specimen-meta:189",
    ],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Columnist Name",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:205",
      "brand-nyt-opinion:specimen-meta:219",
    ],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Body",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:235",
      "brand-nyt-opinion:specimen-meta:252",
    ],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Pull Quotes",
    roleType: "display",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:268",
      "brand-nyt-opinion:specimen-meta:294",
    ],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Section Labels",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:310",
      "brand-nyt-opinion:specimen-meta:329",
    ],
  },
  {
    brandId: "brand-nyt-opinion",
    brandLabel: "NYT Opinion",
    roleLabel: "Letters Header",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-opinion:jsx-label:345",
      "brand-nyt-opinion:specimen-meta:358",
    ],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Product Names",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:164"],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Category Titles",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:210"],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Prices",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:262"],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Badge Text",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:383"],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Descriptions",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:335"],
  },
  {
    brandId: "brand-nyt-store",
    brandLabel: "NYT Store",
    roleLabel: "Cart / CTA",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-store:jsx-label:442"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Feature Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:164"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Trend Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:212"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Body",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:259"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Photo Credits",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:308"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Category Labels",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Medium"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:354"],
  },
  {
    brandId: "brand-nyt-style",
    brandLabel: "NYT Style",
    roleLabel: "Captions",
    roleType: "caption",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["italic"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-style:jsx-label:406"],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Headlines",
    roleType: "headline",
    sourceFontFamily: "Cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-the-athletic:specimen-meta:644"],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Section Titles",
    roleType: "headline",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: [
      "brand-the-athletic:specimen-meta:661",
    ],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Body",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-the-athletic:specimen-meta:680"],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Stat Numbers",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-the-athletic:specimen-meta:730"],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Metadata",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-the-athletic:specimen-meta:744"],
  },
  {
    brandId: "brand-the-athletic",
    brandLabel: "The Athletic",
    roleLabel: "Live Indicator",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-the-athletic:specimen-meta:769"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Headlines",
    roleType: "headline",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:552"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Sub-headlines",
    roleType: "subhead",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Medium"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:567"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Body",
    roleType: "body",
    sourceFontFamily: "Gloucester",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:586"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Verdict / Callout",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:613"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Price / Spec",
    roleType: "ui",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:628"],
  },
  {
    brandId: "brand-wirecutter",
    brandLabel: "Wirecutter",
    roleLabel: "Fine Print",
    roleType: "caption",
    sourceFontFamily: "Franklin Gothic",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-wirecutter:specimen-meta:642"],
  },
  {
    brandId: "brand-nyt-games",
    brandLabel: "NYT Games",
    roleLabel: "Primary Display",
    roleType: "display",
    sourceFontFamily: "Hamburg Serial",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Hamburg Serial",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:jsx-label:504"],
  },
  {
    brandId: "brand-nyt-games",
    brandLabel: "NYT Games",
    roleLabel: "Secondary Display",
    roleType: "display",
    sourceFontFamily: "Stymie",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Stymie",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:jsx-label:562"],
  },
  {
    brandId: "brand-nyt-games",
    brandLabel: "NYT Games",
    roleLabel: "Body / UI",
    roleType: "ui",
    sourceFontFamily: "Hamburg Serial",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Hamburg Serial",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:jsx-label:620"],
  },
  {
    brandId: "brand-nyt-games",
    brandLabel: "NYT Games",
    roleLabel: "Tile Letters",
    roleType: "display",
    sourceFontFamily: "Hamburg Serial",
    sourceWeightsRaw: ["Black"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Hamburg Serial",
    provenance: "design-doc-jsx",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:jsx-label:667"],
  },
  {
    brandId: "brand-nyt-games:canonical",
    brandLabel: "NYT Games Canonical",
    roleLabel: "nyt-franklin",
    roleType: "ui",
    sourceFontFamily: "nyt-franklin",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Hamburg Serial",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:canonical:mapping-line:9"],
    evidenceNote: "Canonical family mapping from game-palettes.ts.",
  },
  {
    brandId: "brand-nyt-games:canonical",
    brandLabel: "NYT Games Canonical",
    roleLabel: "nyt-karnakcondensed",
    roleType: "headline",
    sourceFontFamily: "nyt-karnakcondensed",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["Condensed"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:canonical:mapping-line:10"],
    evidenceNote: "Canonical family mapping from game-palettes.ts.",
  },
  {
    brandId: "brand-nyt-games:canonical",
    brandLabel: "NYT Games Canonical",
    roleLabel: "nyt-karnak",
    roleType: "body",
    sourceFontFamily: "nyt-karnak",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Gloucester",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:canonical:mapping-line:11"],
    evidenceNote: "Canonical family mapping from game-palettes.ts.",
  },
  {
    brandId: "brand-nyt-games:canonical",
    brandLabel: "NYT Games Canonical",
    roleLabel: "nyt-stymie",
    roleType: "display",
    sourceFontFamily: "nyt-stymie",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Stymie",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:canonical:mapping-line:12"],
    evidenceNote: "Canonical family mapping from game-palettes.ts.",
  },
  {
    brandId: "brand-nyt-games:canonical",
    brandLabel: "NYT Games Canonical",
    roleLabel: "nyt-cheltenham",
    roleType: "headline",
    sourceFontFamily: "nyt-cheltenham",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Cheltenham",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: ["brand-nyt-games:canonical:mapping-line:13"],
    evidenceNote: "Canonical family mapping from game-palettes.ts.",
  },
  {
    brandId: "brand-nyt-games:wordle",
    brandLabel: "NYT Games Wordle",
    roleLabel: "Clear Sans",
    roleType: "body",
    sourceFontFamily: "Clear Sans",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Hamburg Serial",
    provenance: "explicit-mapping",
    confidence: "high",
    evidenceIds: [
      "brand-nyt-games:canonical:mapping-line:14",
      "brand-nyt-games:wordle:mapping-line:337",
    ],
  },
  {
    brandId: "brand-nyt-games:connections",
    brandLabel: "NYT Games Connections",
    roleLabel: "nyt-karnakcondensed",
    roleType: "headline",
    sourceFontFamily: "nyt-karnakcondensed",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["Condensed"],
    currentReferenceSubstitute: "Rude Slab Condensed",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:connections:mapping-line:258"],
    evidenceNote: "Game-specific mapping captured from Connections specimen.",
  },
  {
    brandId: "brand-nyt-games:connections",
    brandLabel: "NYT Games Connections",
    roleLabel: "nyt-franklin",
    roleType: "ui",
    sourceFontFamily: "nyt-franklin",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:connections:mapping-line:273"],
    evidenceNote: "Game-specific mapping captured from Connections specimen.",
  },
  {
    brandId: "brand-nyt-games:spelling-bee",
    brandLabel: "NYT Games Spelling Bee",
    roleLabel: "nyt-karnakcondensed",
    roleType: "headline",
    sourceFontFamily: "nyt-karnakcondensed",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["Condensed"],
    currentReferenceSubstitute: "Rude Slab Condensed",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:spelling-bee:mapping-line:286"],
    evidenceNote: "Game-specific mapping captured from Spelling Bee specimen.",
  },
  {
    brandId: "brand-nyt-games:spelling-bee",
    brandLabel: "NYT Games Spelling Bee",
    roleLabel: "nyt-franklin",
    roleType: "ui",
    sourceFontFamily: "nyt-franklin",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:spelling-bee:mapping-line:301"],
    evidenceNote: "Game-specific mapping captured from Spelling Bee specimen.",
  },
  {
    brandId: "brand-nyt-games:tiles",
    brandLabel: "NYT Games Tiles",
    roleLabel: "nyt-karnakcondensed",
    roleType: "headline",
    sourceFontFamily: "nyt-karnakcondensed",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["Condensed"],
    currentReferenceSubstitute: "Rude Slab Condensed",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:tiles:mapping-line:296"],
    evidenceNote: "Game-specific mapping captured from Tiles specimen.",
  },
  {
    brandId: "brand-nyt-games:tiles",
    brandLabel: "NYT Games Tiles",
    roleLabel: "nyt-franklin",
    roleType: "ui",
    sourceFontFamily: "nyt-franklin",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Franklin Gothic",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:tiles:mapping-line:311"],
    evidenceNote: "Game-specific mapping captured from Tiles specimen.",
  },
  {
    brandId: "brand-nyt-games:wordle",
    brandLabel: "NYT Games Wordle",
    roleLabel: "nyt-karnakcondensed",
    roleType: "headline",
    sourceFontFamily: "nyt-karnakcondensed",
    sourceWeightsRaw: ["Bold"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["Condensed"],
    currentReferenceSubstitute: "Rude Slab Condensed",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:wordle:mapping-line:307"],
    evidenceNote: "Game-specific mapping captured from Wordle specimen.",
  },
  {
    brandId: "brand-nyt-games:wordle",
    brandLabel: "NYT Games Wordle",
    roleLabel: "nyt-karnak",
    roleType: "headline",
    sourceFontFamily: "nyt-karnak",
    sourceWeightsRaw: ["Regular"],
    sourceStyles: ["normal"],
    sourceWidthRaw: ["normal"],
    currentReferenceSubstitute: "Stymie",
    provenance: "explicit-mapping",
    confidence: "medium",
    evidenceIds: ["brand-nyt-games:wordle:mapping-line:322"],
    evidenceNote: "Game-specific mapping captured from Wordle specimen.",
  },
] as const;

export const BRAND_FONT_MATCH_RULES: readonly BrandFontMatchRule[] = [
  {
    sourceFamily: "Clear Sans",
    roleTypes: ["body", "ui"],
    preferFamily: ["Hamburg Serial"],
    requireItalic: false,
  },
  {
    sourceFamily: "nyt-franklin",
    roleTypes: ["ui", "caption"],
    preferFamily: ["Franklin Gothic", "Hamburg Serial"],
  },
  {
    sourceFamily: "nyt-karnakcondensed",
    roleTypes: ["headline", "display"],
    preferFamily: ["Rude Slab Condensed", "Cheltenham"],
    requireCondensed: true,
    preferCurrentSubstituteAsTieBreakOnly: true,
  },
  {
    sourceFamily: "nyt-karnak",
    roleTypes: ["body", "subhead"],
    preferFamily: ["Gloucester", "Stymie"],
    demoteDisplayOnlyForBody: true,
  },
  {
    sourceFamily: "nyt-stymie",
    roleTypes: ["display", "headline"],
    preferFamily: ["Stymie"],
    forceTopMatch: "Stymie",
  },
  {
    sourceFamily: "nyt-cheltenham",
    roleTypes: ["headline", "display"],
    preferFamily: ["Cheltenham", "ITC Cheltenham"],
  },
  {
    sourceFamily: "Chomsky",
    roleTypes: ["body", "ui"],
    excludeFamily: ["Chomsky"],
  },
] as const;
