// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/dev-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dev-dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dev-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/fonts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fonts">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/fonts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/groups">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/networks/[entityType]/[entitySlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/networks/[entityType]/[entitySlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/networks/[entityType]/[entitySlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/networks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/networks">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/networks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/scrape-images/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/scrape-images">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/scrape-images/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/shows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shows">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/shows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/social-media/bravo-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social-media/bravo-content">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/social-media/bravo-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/social-media/creator-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social-media/creator-content">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/social-media/creator-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/social-media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social-media">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/social-media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/social-media/reddit/communities/[communityId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social-media/reddit/communities/[communityId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/social-media/reddit/communities/[communityId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/survey-responses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/survey-responses">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/survey-responses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/surveys/[surveyKey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/surveys/[surveyKey]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/surveys/[surveyKey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/surveys/normalized/[surveySlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/surveys/normalized/[surveySlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/surveys/normalized/[surveySlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/surveys/normalized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/surveys/normalized">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/surveys/normalized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/surveys">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/[showSection]/[seasonTab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]/[showSection]/[seasonTab]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/[showSection]/[seasonTab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/[showSection]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]/[showSection]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/[showSection]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/people/[personId]/[[...personTab]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]/people/[personId]/[[...personTab]]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/people/[personId]/[[...personTab]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/seasons/[seasonNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]/seasons/[seasonNumber]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/seasons/[seasonNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/[showId]/seasons/[seasonNumber]/social/week/[weekIndex]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/[showId]/seasons/[seasonNumber]/social/week/[weekIndex]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/[showId]/seasons/[seasonNumber]/social/week/[weekIndex]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trr-shows/people/[personId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trr-shows/people/[personId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trr-shows/people/[personId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/complete">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/finish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/finish">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/finish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bravodle/cover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bravodle/cover">> = Specific
  const handler = {} as typeof import("../../../src/app/bravodle/cover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bravodle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bravodle">> = Specific
  const handler = {} as typeof import("../../../src/app/bravodle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bravodle/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bravodle/play">> = Specific
  const handler = {} as typeof import("../../../src/app/bravodle/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../../src/app/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hub/surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub/surveys">> = Specific
  const handler = {} as typeof import("../../../src/app/hub/surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realations">> = Specific
  const handler = {} as typeof import("../../../src/app/realations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realitease/cover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realitease/cover">> = Specific
  const handler = {} as typeof import("../../../src/app/realitease/cover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realitease/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realitease">> = Specific
  const handler = {} as typeof import("../../../src/app/realitease/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realitease/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realitease/play">> = Specific
  const handler = {} as typeof import("../../../src/app/realitease/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/cast-verdict-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/cast-verdict-demo">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/cast-verdict-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/n/[surveySlug]/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/n/[surveySlug]/play">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/n/[surveySlug]/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhop-s10/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhop-s10">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhop-s10/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhop-s10/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhop-s10/play">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhop-s10/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhop-s10/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhop-s10/results">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhop-s10/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhoslc-s6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhoslc-s6">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhoslc-s6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhoslc-s6/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhoslc-s6/play">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhoslc-s6/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/surveys/rhoslc-s6/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/rhoslc-s6/results">> = Specific
  const handler = {} as typeof import("../../../src/app/surveys/rhoslc-s6/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-of-sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-sale">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-of-sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-auth">> = Specific
  const handler = {} as typeof import("../../../src/app/test-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auth/status/drill-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/status/drill-report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auth/status/drill-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auth/status/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/status/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auth/status/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/covered-shows/[showId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/covered-shows/[showId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/covered-shows/[showId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/covered-shows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/covered-shows">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/covered-shows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dev-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dev-dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dev-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/images/[imageType]/[imageId]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/images/[imageType]/[imageId]/archive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/images/[imageType]/[imageId]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/images/[imageType]/[imageId]/reassign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/images/[imageType]/[imageId]/reassign">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/images/[imageType]/[imageId]/reassign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/images/[imageType]/[imageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/images/[imageType]/[imageId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/images/[imageType]/[imageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/networks-streaming/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/networks-streaming/detail">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/networks-streaming/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/networks-streaming/overrides/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/networks-streaming/overrides/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/networks-streaming/overrides/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/networks-streaming/overrides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/networks-streaming/overrides">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/networks-streaming/overrides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/networks-streaming/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/networks-streaming/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/networks-streaming/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/networks-streaming/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/networks-streaming/sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/networks-streaming/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]/options">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/[questionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/questions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/responses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys/[surveySlug]/runs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/[surveySlug]/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalized-surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalized-surveys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalized-surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/[communityId]/discover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities/[communityId]/discover">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/[communityId]/discover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/[communityId]/episode-discussions/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities/[communityId]/episode-discussions/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/[communityId]/episode-discussions/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/[communityId]/episode-discussions/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities/[communityId]/episode-discussions/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/[communityId]/episode-discussions/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/[communityId]/flares/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities/[communityId]/flares/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/[communityId]/flares/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/[communityId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities/[communityId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/[communityId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/communities">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reddit/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reddit/threads">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reddit/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/scrape/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scrape/import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/scrape/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/scrape/import/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scrape/import/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/scrape/import/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/scrape/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scrape/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/scrape/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/shows/[showKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shows/[showKey]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/shows/[showKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/shows/[showKey]/seasons/[seasonId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shows/[showKey]/seasons/[seasonId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/shows/[showKey]/seasons/[seasonId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/shows/[showKey]/seasons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shows/[showKey]/seasons">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/shows/[showKey]/seasons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/shows/by-trr-show/[trrShowId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shows/by-trr-show/[trrShowId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/shows/by-trr-show/[trrShowId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/shows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shows">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/shows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/social-posts/[postId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social-posts/[postId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/social-posts/[postId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/cast/[castId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/cast/[castId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/cast/[castId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/cast/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/cast/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/cast/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/cast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/cast">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/cast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/episodes/[episodeId]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/episodes/[episodeId]/activate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/episodes/[episodeId]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/episodes/[episodeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/episodes/[episodeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/episodes/[episodeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/episodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/episodes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/episodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/responses/[responseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/responses/[responseId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/responses/[responseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/responses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/[surveyKey]/theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys/[surveyKey]/theme">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/[surveyKey]/theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/surveys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/assets/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/assets/archive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/assets/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/assets/content-type/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/assets/content-type">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/assets/content-type/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/assets/star/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/assets/star">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/assets/star/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/auto-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/auto-count">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/auto-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/detect-text-overlay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/detect-text-overlay">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/detect-text-overlay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/mirror/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/mirror">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/mirror/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/people-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/people-count">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/people-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/tags">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/cast-photos/[photoId]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/cast-photos/[photoId]/variants">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/cast-photos/[photoId]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-assets/[assetId]/auto-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-assets/[assetId]/auto-count">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-assets/[assetId]/auto-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-assets/[assetId]/detect-text-overlay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-assets/[assetId]/detect-text-overlay">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-assets/[assetId]/detect-text-overlay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-assets/[assetId]/mirror/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-assets/[assetId]/mirror">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-assets/[assetId]/mirror/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-assets/[assetId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-assets/[assetId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-assets/[assetId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-assets/[assetId]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-assets/[assetId]/variants">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-assets/[assetId]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-links/[linkId]/context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-links/[linkId]/context">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-links/[linkId]/context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-links/[linkId]/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-links/[linkId]/tags">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-links/[linkId]/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/media-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/media-links">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/media-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/cover-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/cover-photo">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/cover-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/credits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/fandom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/fandom">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/fandom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/gallery/[linkId]/facebank-seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/gallery/[linkId]/facebank-seed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/gallery/[linkId]/facebank-seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/import-fandom/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/import-fandom/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/import-fandom/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/import-fandom/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/import-fandom/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/import-fandom/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/photos/[photoId]/thumbnail-crop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/photos/[photoId]/thumbnail-crop">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/photos/[photoId]/thumbnail-crop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/photos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/refresh-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/refresh-images">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/refresh-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/refresh-images/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/refresh-images/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/refresh-images/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/reprocess-images/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]/reprocess-images/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/reprocess-images/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/[personId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/[personId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/[personId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/resolve-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people/resolve-slug">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/resolve-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/people/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/people">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/people/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/seasons/[seasonId]/assign-backdrops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/seasons/[seasonId]/assign-backdrops">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/seasons/[seasonId]/assign-backdrops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/seasons/[seasonId]/episodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/seasons/[seasonId]/episodes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/seasons/[seasonId]/episodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/seasons/[seasonId]/unassigned-backdrops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/seasons/[seasonId]/unassigned-backdrops">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/seasons/[seasonId]/unassigned-backdrops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/assets/batch-jobs/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/assets/batch-jobs/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/assets/batch-jobs/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/auto-count-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/auto-count-images">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/auto-count-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/bravo/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/bravo/news">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/bravo/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/bravo/videos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/bravo/videos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/bravo/videos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/bravo/videos/sync-thumbnails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/bravo/videos/sync-thumbnails">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/bravo/videos/sync-thumbnails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/cast-matrix/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/cast-matrix/sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/cast-matrix/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/cast-role-members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/cast-role-members">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/cast-role-members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/cast/[personId]/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/cast/[personId]/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/cast/[personId]/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/cast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/cast">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/cast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/google-news/sync/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/google-news/sync/[jobId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/google-news/sync/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/google-news/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/google-news/sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/google-news/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/import-bravo/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/import-bravo/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/preview/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/import-bravo/preview/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/import-bravo/preview/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/links/[linkId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/links/[linkId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/links/[linkId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/links/discover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/links/discover">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/links/discover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/links">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/news">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/refresh-photos/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/refresh-photos/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/refresh-photos/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/refresh/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/refresh/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/refresh/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/roles/[roleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/roles/[roleId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/roles/[roleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets/batch-jobs/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets/batch-jobs/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets/batch-jobs/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/cast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/cast">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/cast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/fandom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/fandom">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/fandom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/import-fandom/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/comments-coverage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/comments-coverage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/comments-coverage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/posts/[platform]/[sourceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/posts/[platform]/[sourceId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/posts/[platform]/[sourceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/week/[weekIndex]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/week/[weekIndex]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/analytics/week/[weekIndex]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest/runs/[runId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest/runs/[runId]/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/ingest/runs/[runId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/jobs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/runs/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/targets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/targets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/social/targets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/survey-cast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/survey-cast">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/[seasonNumber]/survey-cast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/seasons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/seasons">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/seasons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/social-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/social-posts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/social-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/[showId]/surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/[showId]/surveys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/[showId]/surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/resolve-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/resolve-slug">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/resolve-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/trr-api/shows/sync-from-lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trr-api/shows/sync-from-lists">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/trr-api/shows/sync-from-lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/create-survey-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/create-survey-runs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/create-survey-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/episode-progression/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/episode-progression">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/episode-progression/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/debug-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-log">> = Specific
  const handler = {} as typeof import("../../../src/app/api/debug-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/session/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/session/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/session/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/session/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shows/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shows/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shows/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/surveys/[surveySlug]/active-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/[surveySlug]/active-run">> = Specific
  const handler = {} as typeof import("../../../src/app/api/surveys/[surveySlug]/active-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/surveys/[surveySlug]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/[surveySlug]/submit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/surveys/[surveySlug]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/surveys/global-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/global-profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/surveys/global-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/surveys/show-responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/show-responses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/surveys/show-responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/surveys/x/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/x">> = Specific
  const handler = {} as typeof import("../../../src/app/api/surveys/x/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/auth/register/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/register/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bravodle/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/bravodle">> = Specific
  const handler = {} as typeof import("../../../src/app/bravodle/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hub/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../../src/app/hub/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realations/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/realations">> = Specific
  const handler = {} as typeof import("../../../src/app/realations/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realitease/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/realitease">> = Specific
  const handler = {} as typeof import("../../../src/app/realitease/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
